"""Step [0] — document text extraction. Entirely offline: no model is involved.

Fixtures in `data/fixtures/extraction/` are synthetic resumes (invented people),
regenerated by `scripts/make_extraction_fixtures.py`.
"""

from __future__ import annotations

from pathlib import Path

import pytest

from app import extraction
from app.agents.profiler import check_resume
from app.extraction import (
    Extraction,
    FileTooLarge,
    NoTextLayer,
    UnreadableDocument,
    UnsupportedFileType,
    _clean,
    _find_gutter,
    extract,
    load_resume_text,
)
from app.policy import MAX_RESUME_CHARS

FIXTURES = Path(__file__).resolve().parent.parent / "data" / "fixtures" / "extraction"

ONE_COLUMN = "01_simple_1col.pdf"
TWO_COLUMN_INTERLEAVED = "02_two_col_interleaved.pdf"
TWO_COLUMN_BY_COLUMN = "03_two_col_by_column.pdf"
TABLE_BULLETS = "04_table_bullets.pdf"
DOCX = "05_resume.docx"
SCANNED = "06_scanned_image_only.pdf"
TRUNCATED = "07_truncated.pdf"
NOT_A_PDF = "08_not_a_pdf.pdf"
TIGHT_SPACING = "09_tight_spacing.pdf"


def read(name: str) -> bytes:
    return (FIXTURES / name).read_bytes()


def text_of(name: str) -> str:
    return extract(name, read(name)).text


# ---------------------------------------------------------------- _clean


def test_clean_keeps_line_structure_but_collapses_runs():
    assert _clean("a  b\t c\r\n\r\n\r\n\r\nd  ") == "a b c\n\nd"


def test_clean_maps_unmappable_glyphs_to_a_bullet():
    """pdfminer emits (cid:NNN) for a glyph it cannot map — Symbol/Wingdings
    bullets hit this constantly. Left alone it reaches the model as junk."""
    assert _clean("(cid:127) Built a pipeline") == "• Built a pipeline"


def test_clean_strips_control_characters_including_nul():
    assert _clean("Ravi\x00 Menon\x07") == "Ravi Menon"


def test_clean_leaves_resume_punctuation_alone():
    line = "Mar 2021 – Present | 34% | +91 90000 11111 | a.b@example.invalid"
    assert _clean(line) == line


# ---------------------------------------------------------------- _find_gutter


def word(x0: float, x1: float, top: float = 100.0) -> dict:
    return {"x0": x0, "x1": x1, "top": top, "bottom": top + 10.0}


def test_find_gutter_returns_none_without_words():
    assert _find_gutter([], 600.0, 800.0) is None


def test_find_gutter_finds_a_real_two_column_gap():
    words = [word(40, 240) for _ in range(20)] + [word(330, 520) for _ in range(20)]
    found = _find_gutter(words, 600.0, 800.0)
    assert found is not None
    gutter_x, cut = found
    assert 240 < gutter_x < 330
    assert cut == 0.0


def test_find_gutter_ignores_a_narrow_accidental_channel():
    """The Caliber bug: on a single-column page, inter-word spaces line up and a
    ~4pt channel wins, after which straddling words are emitted twice in halves.
    A column gap is tens of points wide; anything narrower is an accident."""
    words = [word(40, 296) for _ in range(20)] + [word(300, 520) for _ in range(20)]
    assert _find_gutter(words, 600.0, 800.0) is None


def test_find_gutter_needs_a_real_share_of_words_on_both_sides():
    words = [word(40, 240) for _ in range(40)] + [word(330, 520) for _ in range(2)]
    assert _find_gutter(words, 600.0, 800.0) is None


# ---------------------------------------------------------------- PDF, one column


def test_single_column_pdf_is_read_as_single_column():
    result = extract(ONE_COLUMN, read(ONE_COLUMN))
    assert result.layout == "single-column"
    assert result.pages == 2
    assert result.is_usable


def test_single_column_lines_are_not_sliced_in_half():
    """Regression for the false-positive column split: the guard is load-bearing,
    not decorative."""
    assert (
        "• Built a FastAPI route-planning service used by 300 depot operators."
        in text_of(ONE_COLUMN)
    )


def test_without_the_clearance_guard_the_same_page_is_corrupted(monkeypatch):
    """Documents the Caliber behaviour this module deviates from (RULEBOOK §16 O18)."""
    monkeypatch.setattr(extraction, "_MIN_CLEARANCE", 0.0)
    corrupted = text_of(ONE_COLUMN)
    assert (
        "• Built a FastAPI route-planning service used by 300 depot operators."
        not in corrupted
    )


def test_both_pages_of_a_multi_page_pdf_are_read():
    body = text_of(ONE_COLUMN)
    assert "Senior Backend Engineer, Tavira Payments" in body  # page 1
    assert "Junior Developer, Sarath Analytics" in body  # page 2


# ---------------------------------------------------------------- PDF, two columns


@pytest.mark.parametrize("name", [TWO_COLUMN_INTERLEAVED, TWO_COLUMN_BY_COLUMN])
def test_two_column_pdf_is_detected(name):
    assert extract(name, read(name)).layout == "multi-column"


@pytest.mark.parametrize("name", [TWO_COLUMN_INTERLEAVED, TWO_COLUMN_BY_COLUMN])
def test_two_column_sidebar_does_not_interleave_into_the_job_history(name):
    """The reason pypdf was rejected: read positionally, a skills sidebar lands
    inside the job titles. The whole left column must come first."""
    body = text_of(name)
    assert body.index("Neelkanth Retail Systems") < body.index("SKILLS")
    assert body.index("Marisol Consulting") < body.index("Python, Scala, SQL")


def test_draw_order_does_not_change_the_result():
    """Same resume, emitted line-by-line across both columns vs whole-column —
    the reader must not care."""
    assert text_of(TWO_COLUMN_INTERLEAVED) == text_of(TWO_COLUMN_BY_COLUMN)


# ---------------------------------------------------------- PDF, tight spacing


def test_a_tightly_spaced_page_still_yields_separate_words():
    body = text_of(TIGHT_SPACING)
    assert "Solvent Labs India, Software Engineer" in body
    assert "Bachelor of Engineering, Ghatkopar Institute of Technology, 2019" in body
    assert "Strong focus on system optimization, profiling and release hygiene." in body


def test_a_tightly_spaced_page_is_still_read_as_one_column():
    result = extract(TIGHT_SPACING, read(TIGHT_SPACING))
    assert result.layout == "single-column"
    assert result.is_usable


def test_with_pdfplumbers_default_tolerance_the_same_page_loses_its_spaces(monkeypatch):
    """Pins `_TOLERANCE` (RULEBOOK §16 O21). Most PDFs store no space characters;
    at the 3 pt default this page's 2.2 pt word gaps read as intra-word, the text
    still passes every check here, and the damage only lands downstream, where
    the Profiler verifies each claim as a verbatim substring."""
    monkeypatch.setattr(extraction, "_TOLERANCE", {})
    fused = text_of(TIGHT_SPACING)
    assert "BachelorofEngineering" in fused
    assert "Bachelor of Engineering" not in fused
    assert "SoftwareEngineer" in fused


def test_a_flat_tolerance_would_shatter_the_heading_where_a_ratio_holds_it(monkeypatch):
    """Why the constant is a ratio and not a flat point value: the 20 pt name on
    this page is tracked 2.0 pt apart, which a flat 1.5 pt reads as word gaps,
    while 0.15 x 20 pt leaves 3.0 pt of headroom. Both settings split the 10 pt
    body correctly — only the ratio survives both font sizes."""
    assert "Priya Deshmukh" in text_of(TIGHT_SPACING)
    monkeypatch.setattr(extraction, "_TOLERANCE", {"x_tolerance": 1.5})
    assert "P r i y a D e s h m u k h" in text_of(TIGHT_SPACING)


@pytest.mark.parametrize("name", [ONE_COLUMN, TWO_COLUMN_INTERLEAVED])
def test_every_pdfplumber_call_is_given_the_same_tolerance(name, monkeypatch):
    """The column path crops the page and extracts again; if that call kept the
    library default, a two-column page would decide where words begin on
    different rules from a one-column one."""
    from pdfplumber.page import Page

    seen: list[dict] = []
    for method in ("extract_text", "extract_words"):
        original = getattr(Page, method)

        def spy(self, *args, _original=original, **kwargs):
            seen.append(kwargs)
            return _original(self, *args, **kwargs)

        monkeypatch.setattr(Page, method, spy)

    extract(name, read(name))
    assert seen
    assert all(call.get("x_tolerance_ratio") == 0.15 for call in seen), seen


# ---------------------------------------------------------------- PDF, tables


def test_pdf_table_rows_survive_as_lines():
    body = text_of(TABLE_BULLETS)
    assert "QA Automation Lead Vellore Softworks 2022–Present Playwright" in body
    assert (
        "• Built a flaky-test quarantine bot; false-failure rate fell from 9% to under 1%."
        in body
    )


# ---------------------------------------------------------------- DOCX


def test_docx_table_cells_are_extracted_with_separators():
    body = text_of(DOCX)
    assert "Lead Product Designer | Palani Health | Feb 2022 – Present" in body
    assert "UX Designer | Ambalika Labs | Aug 2017 – May 2019" in body


def test_docx_tables_stay_under_their_own_heading():
    """DEVIATION 3 (O20): Caliber appends every table after all paragraphs, so the
    Experience table lands below Education. Body order keeps it where it belongs."""
    body = text_of(DOCX)
    assert body.index("Experience") < body.index("Lead Product Designer")
    assert body.index("Lead Product Designer") < body.index("Selected work")


def test_docx_layout_label_and_page_count():
    result = extract(DOCX, read(DOCX))
    assert result.layout == "docx"
    assert result.pages == 1


def test_corrupt_docx_is_an_unreadable_document():
    with pytest.raises(UnreadableDocument):
        extract("resume.docx", b"not a zip file at all")


# ---------------------------------------------------------------- failure modes


def test_image_only_pdf_returns_empty_rather_than_raising():
    """A scan parses fine — it simply has no text layer. The caller decides."""
    result = extract(SCANNED, read(SCANNED))
    assert result.layout == "empty"
    assert result.text == ""
    assert not result.is_usable


@pytest.mark.parametrize("name", [TRUNCATED, NOT_A_PDF])
def test_corrupt_pdf_becomes_one_domain_error(name):
    with pytest.raises(UnreadableDocument) as caught:
        extract(name, read(name))
    assert "corrupt" in str(caught.value)


def test_unsupported_extension_is_refused_before_parsing():
    with pytest.raises(UnsupportedFileType):
        extract("resume.txt", b"plain text is not an upload path")


def test_oversized_upload_is_refused_before_parsing():
    with pytest.raises(FileTooLarge):
        extract("resume.pdf", b"x" * (extraction.MAX_UPLOAD_BYTES + 1))


def test_every_failure_is_still_a_value_error():
    """Caliber's callers catch ValueError; the subclasses must not break them."""
    for error in (UnsupportedFileType, FileTooLarge, UnreadableDocument, NoTextLayer):
        assert issubclass(error, ValueError)


# ---------------------------------------------------------------- is_usable gate


@pytest.mark.parametrize(
    "length, usable",
    [(0, False), (extraction.MIN_USEFUL_CHARS - 1, False), (extraction.MIN_USEFUL_CHARS, True)],
)
def test_is_usable_threshold(length, usable):
    assert Extraction("x" * length, 1, "single-column").is_usable is usable


# ---------------------------------------------------------------- load_resume_text


def test_load_resume_text_hands_the_profiler_a_plain_string():
    source = load_resume_text(ONE_COLUMN, read(ONE_COLUMN))
    assert source.text.startswith("Ravi Menon")
    assert not source.was_clipped
    assert source.extraction.layout == "single-column"


def test_load_resume_text_refuses_a_scan_before_any_model_call():
    """The one case that must never reach the model: an empty string costs
    tokens and comes back as a confidently invented profile."""
    with pytest.raises(NoTextLayer) as caught:
        load_resume_text(SCANNED, read(SCANNED))
    assert "scan" in str(caught.value)


def test_load_resume_text_reports_clipping_instead_of_truncating_silently(monkeypatch):
    long_text = "Ravi Menon is a backend engineer. " * 4000
    monkeypatch.setattr(
        extraction, "extract", lambda *_: Extraction(long_text, 1, "single-column")
    )
    source = load_resume_text("resume.pdf", b"ignored")
    assert len(source.text) == MAX_RESUME_CHARS
    assert source.was_clipped
    assert source.clipped_chars == len(long_text) - MAX_RESUME_CHARS


def test_extracted_text_is_accepted_by_the_profiler_input_check():
    """Step [0] output is valid step [1] input — the seam holds without a call."""
    source = load_resume_text(ONE_COLUMN, read(ONE_COLUMN))
    assert check_resume(source.text) == source.text.strip()
